# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resource/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 747)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app/icons/logo/pyphone48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.screen = Screen(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setMinimumSize(QtCore.QSize(0, 0))
        self.screen.setSizeIncrement(QtCore.QSize(0, 0))
        self.screen.setStyleSheet("")
        self.screen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.screen.setObjectName("screen")
        self.gridLayout.addWidget(self.screen, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setEnabled(True)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/app/icons/app/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon1)
        self.actionStart.setShortcutVisibleInContextMenu(False)
        self.actionStart.setObjectName("actionStart")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/app/icons/app/donate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon2)
        self.actionDonate.setObjectName("actionDonate")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/app/icons/app/disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionShare = QtWidgets.QAction(MainWindow)
        self.actionShare.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/app/icons/app/plugin_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShare.setIcon(icon4)
        self.actionShare.setObjectName("actionShare")
        self.actionRemote_screen = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/app/icons/app/customer_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_screen.setIcon(icon5)
        self.actionRemote_screen.setObjectName("actionRemote_screen")
        self.actionSend_Text = QtWidgets.QAction(MainWindow)
        self.actionSend_Text.setObjectName("actionSend_Text")
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/app/icons/app/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon6)
        self.actionHome.setObjectName("actionHome")
        self.actionLock_Unlocak = QtWidgets.QAction(MainWindow)
        self.actionLock_Unlocak.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/app/icons/app/unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLock_Unlocak.setIcon(icon7)
        self.actionLock_Unlocak.setObjectName("actionLock_Unlocak")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.actionMenu = QtWidgets.QAction(MainWindow)
        self.actionMenu.setObjectName("actionMenu")
        self.actionSend_text = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/app/icons/app/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSend_text.setIcon(icon8)
        self.actionSend_text.setObjectName("actionSend_text")
        self.actionDisable_share = QtWidgets.QAction(MainWindow)
        self.actionDisable_share.setEnabled(False)
        self.actionDisable_share.setObjectName("actionDisable_share")
        self.actionRecorder = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/app/icons/app/recording.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecorder.setIcon(icon9)
        self.actionRecorder.setObjectName("actionRecorder")
        self.actionScreenshots = QtWidgets.QAction(MainWindow)
        self.actionScreenshots.setObjectName("actionScreenshots")
        self.actionStop_recorder = QtWidgets.QAction(MainWindow)
        self.actionStop_recorder.setEnabled(False)
        self.actionStop_recorder.setObjectName("actionStop_recorder")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShare)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRemote_screen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionLock_Unlocak)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionHome)
        self.menuEdit.addAction(self.actionBack)
        self.menuEdit.addAction(self.actionMenu)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRecorder)
        self.menuEdit.addAction(self.actionScreenshots)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSend_text)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyPhone"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.actionStart.setText(_translate("MainWindow", "&Start"))
        self.actionStart.setShortcut(_translate("MainWindow", "F5"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.actionStop.setText(_translate("MainWindow", "S&top"))
        self.actionStop.setShortcut(_translate("MainWindow", "F4"))
        self.actionShare.setText(_translate("MainWindow", "Enable s&hare"))
        self.actionRemote_screen.setText(_translate("MainWindow", "&Connect remote screen ..."))
        self.actionSend_Text.setText(_translate("MainWindow", "Send Text"))
        self.actionHome.setText(_translate("MainWindow", "&Home"))
        self.actionHome.setShortcut(_translate("MainWindow", "Home"))
        self.actionLock_Unlocak.setText(_translate("MainWindow", "&Lock/Unlocak"))
        self.actionLock_Unlocak.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionBack.setText(_translate("MainWindow", "&Back"))
        self.actionMenu.setText(_translate("MainWindow", "&Menu"))
        self.actionSend_text.setText(_translate("MainWindow", "Send te&xt"))
        self.actionSend_text.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionDisable_share.setText(_translate("MainWindow", "&Disable share"))
        self.actionRecorder.setText(_translate("MainWindow", "Start &video recorder..."))
        self.actionRecorder.setShortcut(_translate("MainWindow", "F9"))
        self.actionScreenshots.setText(_translate("MainWindow", "S&creenshots"))
        self.actionStop_recorder.setText(_translate("MainWindow", "Stop video recorder..."))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))

from widgets.screen import Screen
import icons_rc
